server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/sql_study?useSSL=false&serverTimezone=UTC
    username: root
    password: yangjunming123
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  thymeleaf:
    cache: false #使用Thymeleaf模板引擎，关闭缓存

# MyBatis 配置（新增部分）
mybatis:
  mapper-locations: classpath:mapper/*.xml  # XML映射文件路径
  type-aliases-package: com.example.demo.Entity  # 实体类包路径（根据实际修改）
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名自动映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志（调试用）

# pagehelper 配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: pageNum=pageNum,pageSize=pageSize,count=countSql,reasonable=reasonable,orderBy=orderByClause
  rowBoundsWithCount: true
  pageSizeZero: true
